[package]
name = "disint-model"
version = "0.1.0"
authors = ["Wonwoo Choi <chwo9843@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
derive_builder = "0.9.0"

[dependencies.serde]
version = "1.0.122"
features = ["derive"]
